export const ACTIONS = {
  SET_IS_SEARCHING: "SET_IS_SEARCHING",
  TOGGLE_ADVANCED_SEARCH: "TOGGLE_ADVANCED_SEARCH",
  SET_BASE_VALUES: "SET_BASE_VALUES",
  SET_SLIDER_VALUE: "SET_SLIDER_VALUE",
  TOGGLE_BUTTON_GROUP_VALUE: "TOGGLE_BUTTON_GROUP_VALUE",
  SET_SEARCH_RESULTS: "SET_SEARCH_RESULTS"
};

export const SEARCH_REDUCER_KEY = "base";

export default ACTIONS;
