// <auto-generated />
namespace Triven.Data.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addForeignKeytoClassification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addForeignKeytoClassification));
        
        string IMigrationMetadata.Id
        {
            get { return "201703251633303_add ForeignKey to Classification"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
