namespace Triven.Data.EntityFramework.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class ForeignKeyMadness01 : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Subscription", "ApplicationUser_Id", "dbo.Users");
            DropForeignKey("dbo.VehicleDescription", "Vehicle_Id", "dbo.Vehicle");
            DropForeignKey("dbo.VehicleFeature", "Vehicle_Id", "dbo.Vehicle");
            DropForeignKey("dbo.VehicleImage", "Vehicle_Id", "dbo.Vehicle");
            DropForeignKey("dbo.Vehicle", "MainImage_Id", "dbo.Image");
            DropForeignKey("dbo.Vehicle", "VehicleModel_Id", "dbo.VehicleModel");
            DropForeignKey("dbo.VehicleFeature", "Feature_Id", "dbo.Feature");
            DropForeignKey("dbo.VehicleImage", "Image_Id", "dbo.Image");
            DropForeignKey("dbo.VehicleFault", "VehicleReport_Id", "dbo.VehicleReport");
            DropIndex("dbo.Subscription", new[] { "ApplicationUser_Id" });
            DropIndex("dbo.VehicleDescription", new[] { "Vehicle_Id" });
            DropIndex("dbo.Vehicle", new[] { "MainImage_Id" });
            DropIndex("dbo.Vehicle", new[] { "VehicleModel_Id" });
            DropIndex("dbo.VehicleFeature", new[] { "Feature_Id" });
            DropIndex("dbo.VehicleFeature", new[] { "Vehicle_Id" });
            DropIndex("dbo.VehicleImage", new[] { "Image_Id" });
            DropIndex("dbo.VehicleImage", new[] { "Vehicle_Id" });
            DropIndex("dbo.VehicleFault", new[] { "VehicleReport_Id" });
            RenameColumn(table: "dbo.Classification", name: "Creator_Id", newName: "CreatorId");
            RenameColumn(table: "dbo.Classification", name: "Modifier_Id", newName: "ModifierId");
            RenameColumn(table: "dbo.Classification", name: "Remover_Id", newName: "RemoverId");
            RenameColumn(table: "dbo.ClassificationType", name: "Creator_Id", newName: "CreatorId");
            RenameColumn(table: "dbo.ClassificationType", name: "Modifier_Id", newName: "ModifierId");
            RenameColumn(table: "dbo.ClassificationType", name: "Remover_Id", newName: "RemoverId");
            RenameColumn(table: "dbo.Feature", name: "Creator_Id", newName: "CreatorId");
            RenameColumn(table: "dbo.Feature", name: "Modifier_Id", newName: "ModifierId");
            RenameColumn(table: "dbo.Feature", name: "Remover_Id", newName: "RemoverId");
            RenameColumn(table: "dbo.Image", name: "Creator_Id", newName: "CreatorId");
            RenameColumn(table: "dbo.Image", name: "Modifier_Id", newName: "ModifierId");
            RenameColumn(table: "dbo.Image", name: "Remover_Id", newName: "RemoverId");
            RenameColumn(table: "dbo.Subscription", name: "ApplicationUser_Id", newName: "ApplicationUserId");
            RenameColumn(table: "dbo.Subscription", name: "Creator_Id", newName: "CreatorId");
            RenameColumn(table: "dbo.Subscription", name: "Modifier_Id", newName: "ModifierId");
            RenameColumn(table: "dbo.Subscription", name: "Remover_Id", newName: "RemoverId");
            RenameColumn(table: "dbo.VehicleDescription", name: "Creator_Id", newName: "CreatorId");
            RenameColumn(table: "dbo.VehicleDescription", name: "Modifier_Id", newName: "ModifierId");
            RenameColumn(table: "dbo.VehicleDescription", name: "Remover_Id", newName: "RemoverId");
            RenameColumn(table: "dbo.VehicleDescription", name: "Vehicle_Id", newName: "VehicleId");
            RenameColumn(table: "dbo.Vehicle", name: "ApplicationUser_Id", newName: "ApplicationUserId");
            RenameColumn(table: "dbo.Vehicle", name: "Creator_Id", newName: "CreatorId");
            RenameColumn(table: "dbo.VehicleFeature", name: "Vehicle_Id", newName: "VehicleId");
            RenameColumn(table: "dbo.VehicleImage", name: "Vehicle_Id", newName: "VehicleId");
            RenameColumn(table: "dbo.Vehicle", name: "MainImage_Id", newName: "MainImageId");
            RenameColumn(table: "dbo.Vehicle", name: "Modifier_Id", newName: "ModifierId");
            RenameColumn(table: "dbo.Vehicle", name: "Remover_Id", newName: "RemoverId");
            RenameColumn(table: "dbo.Vehicle", name: "VehicleModel_Id", newName: "VehicleModelId");
            RenameColumn(table: "dbo.VehicleFeature", name: "Creator_Id", newName: "CreatorId");
            RenameColumn(table: "dbo.VehicleFeature", name: "Feature_Id", newName: "FeatureId");
            RenameColumn(table: "dbo.VehicleFeature", name: "Modifier_Id", newName: "ModifierId");
            RenameColumn(table: "dbo.VehicleFeature", name: "Remover_Id", newName: "RemoverId");
            RenameColumn(table: "dbo.VehicleImage", name: "Creator_Id", newName: "CreatorId");
            RenameColumn(table: "dbo.VehicleImage", name: "Image_Id", newName: "ImageId");
            RenameColumn(table: "dbo.VehicleImage", name: "Modifier_Id", newName: "ModifierId");
            RenameColumn(table: "dbo.VehicleImage", name: "Remover_Id", newName: "RemoverId");
            RenameColumn(table: "dbo.VehicleReport", name: "Creator_Id", newName: "CreatorId");
            RenameColumn(table: "dbo.VehicleFault", name: "VehicleReport_Id", newName: "VehicleReportId");
            RenameColumn(table: "dbo.VehicleReport", name: "Modifier_Id", newName: "ModifierId");
            RenameColumn(table: "dbo.VehicleReport", name: "Remover_Id", newName: "RemoverId");
            RenameColumn(table: "dbo.VehicleReportItem", name: "Parent_Id", newName: "ParentId");
            RenameColumn(table: "dbo.VehicleFault", name: "Creator_Id", newName: "CreatorId");
            RenameColumn(table: "dbo.VehicleFault", name: "Image_Id", newName: "ImageId");
            RenameColumn(table: "dbo.VehicleFault", name: "Modifier_Id", newName: "ModifierId");
            RenameColumn(table: "dbo.VehicleFault", name: "Remover_Id", newName: "RemoverId");
            RenameColumn(table: "dbo.VehicleReportItem", name: "Creator_Id", newName: "CreatorId");
            RenameColumn(table: "dbo.VehicleReportItem", name: "Modifier_Id", newName: "ModifierId");
            RenameColumn(table: "dbo.VehicleReportItem", name: "Remover_Id", newName: "RemoverId");
            RenameColumn(table: "dbo.VehicleReview", name: "Creator_Id", newName: "CreatorId");
            RenameColumn(table: "dbo.VehicleReview", name: "Modifier_Id", newName: "ModifierId");
            RenameColumn(table: "dbo.VehicleReview", name: "Remover_Id", newName: "RemoverId");
            RenameColumn(table: "dbo.VehicleModel", name: "Creator_Id", newName: "CreatorId");
            RenameColumn(table: "dbo.VehicleModel", name: "Modifier_Id", newName: "ModifierId");
            RenameColumn(table: "dbo.VehicleModel", name: "Remover_Id", newName: "RemoverId");
            RenameIndex(table: "dbo.Classification", name: "IX_Creator_Id", newName: "IX_CreatorId");
            RenameIndex(table: "dbo.Classification", name: "IX_Modifier_Id", newName: "IX_ModifierId");
            RenameIndex(table: "dbo.Classification", name: "IX_Remover_Id", newName: "IX_RemoverId");
            RenameIndex(table: "dbo.ClassificationType", name: "IX_Creator_Id", newName: "IX_CreatorId");
            RenameIndex(table: "dbo.ClassificationType", name: "IX_Modifier_Id", newName: "IX_ModifierId");
            RenameIndex(table: "dbo.ClassificationType", name: "IX_Remover_Id", newName: "IX_RemoverId");
            RenameIndex(table: "dbo.Feature", name: "IX_Creator_Id", newName: "IX_CreatorId");
            RenameIndex(table: "dbo.Feature", name: "IX_Modifier_Id", newName: "IX_ModifierId");
            RenameIndex(table: "dbo.Feature", name: "IX_Remover_Id", newName: "IX_RemoverId");
            RenameIndex(table: "dbo.Image", name: "IX_Creator_Id", newName: "IX_CreatorId");
            RenameIndex(table: "dbo.Image", name: "IX_Modifier_Id", newName: "IX_ModifierId");
            RenameIndex(table: "dbo.Image", name: "IX_Remover_Id", newName: "IX_RemoverId");
            RenameIndex(table: "dbo.Subscription", name: "IX_Creator_Id", newName: "IX_CreatorId");
            RenameIndex(table: "dbo.Subscription", name: "IX_Modifier_Id", newName: "IX_ModifierId");
            RenameIndex(table: "dbo.Subscription", name: "IX_Remover_Id", newName: "IX_RemoverId");
            RenameIndex(table: "dbo.VehicleDescription", name: "IX_Creator_Id", newName: "IX_CreatorId");
            RenameIndex(table: "dbo.VehicleDescription", name: "IX_Modifier_Id", newName: "IX_ModifierId");
            RenameIndex(table: "dbo.VehicleDescription", name: "IX_Remover_Id", newName: "IX_RemoverId");
            RenameIndex(table: "dbo.Vehicle", name: "IX_ApplicationUser_Id", newName: "IX_ApplicationUserId");
            RenameIndex(table: "dbo.Vehicle", name: "IX_Creator_Id", newName: "IX_CreatorId");
            RenameIndex(table: "dbo.Vehicle", name: "IX_Modifier_Id", newName: "IX_ModifierId");
            RenameIndex(table: "dbo.Vehicle", name: "IX_Remover_Id", newName: "IX_RemoverId");
            RenameIndex(table: "dbo.VehicleFeature", name: "IX_Creator_Id", newName: "IX_CreatorId");
            RenameIndex(table: "dbo.VehicleFeature", name: "IX_Modifier_Id", newName: "IX_ModifierId");
            RenameIndex(table: "dbo.VehicleFeature", name: "IX_Remover_Id", newName: "IX_RemoverId");
            RenameIndex(table: "dbo.VehicleImage", name: "IX_Creator_Id", newName: "IX_CreatorId");
            RenameIndex(table: "dbo.VehicleImage", name: "IX_Modifier_Id", newName: "IX_ModifierId");
            RenameIndex(table: "dbo.VehicleImage", name: "IX_Remover_Id", newName: "IX_RemoverId");
            RenameIndex(table: "dbo.VehicleReport", name: "IX_Creator_Id", newName: "IX_CreatorId");
            RenameIndex(table: "dbo.VehicleReport", name: "IX_Modifier_Id", newName: "IX_ModifierId");
            RenameIndex(table: "dbo.VehicleReport", name: "IX_Remover_Id", newName: "IX_RemoverId");
            RenameIndex(table: "dbo.VehicleFault", name: "IX_Image_Id", newName: "IX_ImageId");
            RenameIndex(table: "dbo.VehicleFault", name: "IX_Creator_Id", newName: "IX_CreatorId");
            RenameIndex(table: "dbo.VehicleFault", name: "IX_Modifier_Id", newName: "IX_ModifierId");
            RenameIndex(table: "dbo.VehicleFault", name: "IX_Remover_Id", newName: "IX_RemoverId");
            RenameIndex(table: "dbo.VehicleReportItem", name: "IX_Parent_Id", newName: "IX_ParentId");
            RenameIndex(table: "dbo.VehicleReportItem", name: "IX_Creator_Id", newName: "IX_CreatorId");
            RenameIndex(table: "dbo.VehicleReportItem", name: "IX_Modifier_Id", newName: "IX_ModifierId");
            RenameIndex(table: "dbo.VehicleReportItem", name: "IX_Remover_Id", newName: "IX_RemoverId");
            RenameIndex(table: "dbo.VehicleReview", name: "IX_Creator_Id", newName: "IX_CreatorId");
            RenameIndex(table: "dbo.VehicleReview", name: "IX_Modifier_Id", newName: "IX_ModifierId");
            RenameIndex(table: "dbo.VehicleReview", name: "IX_Remover_Id", newName: "IX_RemoverId");
            RenameIndex(table: "dbo.VehicleModel", name: "IX_Creator_Id", newName: "IX_CreatorId");
            RenameIndex(table: "dbo.VehicleModel", name: "IX_Modifier_Id", newName: "IX_ModifierId");
            RenameIndex(table: "dbo.VehicleModel", name: "IX_Remover_Id", newName: "IX_RemoverId");
            AlterColumn("dbo.Subscription", "ApplicationUserId", c => c.Int(nullable: false));
            AlterColumn("dbo.VehicleDescription", "VehicleId", c => c.Int(nullable: false));
            AlterColumn("dbo.Vehicle", "MainImageId", c => c.Int(nullable: false));
            AlterColumn("dbo.Vehicle", "VehicleModelId", c => c.Int(nullable: false));
            AlterColumn("dbo.VehicleFeature", "FeatureId", c => c.Int(nullable: false));
            AlterColumn("dbo.VehicleFeature", "VehicleId", c => c.Int(nullable: false));
            AlterColumn("dbo.VehicleImage", "ImageId", c => c.Int(nullable: false));
            AlterColumn("dbo.VehicleImage", "VehicleId", c => c.Int(nullable: false));
            AlterColumn("dbo.VehicleFault", "VehicleReportId", c => c.Int(nullable: false));
            CreateIndex("dbo.Subscription", "ApplicationUserId");
            CreateIndex("dbo.VehicleDescription", "VehicleId");
            CreateIndex("dbo.Vehicle", "MainImageId");
            CreateIndex("dbo.Vehicle", "VehicleModelId");
            CreateIndex("dbo.VehicleFeature", "FeatureId");
            CreateIndex("dbo.VehicleFeature", "VehicleId");
            CreateIndex("dbo.VehicleImage", "VehicleId");
            CreateIndex("dbo.VehicleImage", "ImageId");
            CreateIndex("dbo.VehicleFault", "VehicleReportId");
            AddForeignKey("dbo.Subscription", "ApplicationUserId", "dbo.Users", "Id", cascadeDelete: false);
            AddForeignKey("dbo.VehicleDescription", "VehicleId", "dbo.Vehicle", "Id", cascadeDelete: false);
            AddForeignKey("dbo.VehicleFeature", "VehicleId", "dbo.Vehicle", "Id", cascadeDelete: false);
            AddForeignKey("dbo.VehicleImage", "VehicleId", "dbo.Vehicle", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Vehicle", "MainImageId", "dbo.Image", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Vehicle", "VehicleModelId", "dbo.VehicleModel", "Id", cascadeDelete: false);
            AddForeignKey("dbo.VehicleFeature", "FeatureId", "dbo.Feature", "Id", cascadeDelete: false);
            AddForeignKey("dbo.VehicleImage", "ImageId", "dbo.Image", "Id", cascadeDelete: false);
            AddForeignKey("dbo.VehicleFault", "VehicleReportId", "dbo.VehicleReport", "Id", cascadeDelete: false);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.VehicleFault", "VehicleReportId", "dbo.VehicleReport");
            DropForeignKey("dbo.VehicleImage", "ImageId", "dbo.Image");
            DropForeignKey("dbo.VehicleFeature", "FeatureId", "dbo.Feature");
            DropForeignKey("dbo.Vehicle", "VehicleModelId", "dbo.VehicleModel");
            DropForeignKey("dbo.Vehicle", "MainImageId", "dbo.Image");
            DropForeignKey("dbo.VehicleImage", "VehicleId", "dbo.Vehicle");
            DropForeignKey("dbo.VehicleFeature", "VehicleId", "dbo.Vehicle");
            DropForeignKey("dbo.VehicleDescription", "VehicleId", "dbo.Vehicle");
            DropForeignKey("dbo.Subscription", "ApplicationUserId", "dbo.Users");
            DropIndex("dbo.VehicleFault", new[] { "VehicleReportId" });
            DropIndex("dbo.VehicleImage", new[] { "ImageId" });
            DropIndex("dbo.VehicleImage", new[] { "VehicleId" });
            DropIndex("dbo.VehicleFeature", new[] { "VehicleId" });
            DropIndex("dbo.VehicleFeature", new[] { "FeatureId" });
            DropIndex("dbo.Vehicle", new[] { "VehicleModelId" });
            DropIndex("dbo.Vehicle", new[] { "MainImageId" });
            DropIndex("dbo.VehicleDescription", new[] { "VehicleId" });
            DropIndex("dbo.Subscription", new[] { "ApplicationUserId" });
            AlterColumn("dbo.VehicleFault", "VehicleReportId", c => c.Int());
            AlterColumn("dbo.VehicleImage", "VehicleId", c => c.Int());
            AlterColumn("dbo.VehicleImage", "ImageId", c => c.Int());
            AlterColumn("dbo.VehicleFeature", "VehicleId", c => c.Int());
            AlterColumn("dbo.VehicleFeature", "FeatureId", c => c.Int());
            AlterColumn("dbo.Vehicle", "VehicleModelId", c => c.Int());
            AlterColumn("dbo.Vehicle", "MainImageId", c => c.Int());
            AlterColumn("dbo.VehicleDescription", "VehicleId", c => c.Int());
            AlterColumn("dbo.Subscription", "ApplicationUserId", c => c.Int());
            RenameIndex(table: "dbo.VehicleModel", name: "IX_RemoverId", newName: "IX_Remover_Id");
            RenameIndex(table: "dbo.VehicleModel", name: "IX_ModifierId", newName: "IX_Modifier_Id");
            RenameIndex(table: "dbo.VehicleModel", name: "IX_CreatorId", newName: "IX_Creator_Id");
            RenameIndex(table: "dbo.VehicleReview", name: "IX_RemoverId", newName: "IX_Remover_Id");
            RenameIndex(table: "dbo.VehicleReview", name: "IX_ModifierId", newName: "IX_Modifier_Id");
            RenameIndex(table: "dbo.VehicleReview", name: "IX_CreatorId", newName: "IX_Creator_Id");
            RenameIndex(table: "dbo.VehicleReportItem", name: "IX_RemoverId", newName: "IX_Remover_Id");
            RenameIndex(table: "dbo.VehicleReportItem", name: "IX_ModifierId", newName: "IX_Modifier_Id");
            RenameIndex(table: "dbo.VehicleReportItem", name: "IX_CreatorId", newName: "IX_Creator_Id");
            RenameIndex(table: "dbo.VehicleReportItem", name: "IX_ParentId", newName: "IX_Parent_Id");
            RenameIndex(table: "dbo.VehicleFault", name: "IX_RemoverId", newName: "IX_Remover_Id");
            RenameIndex(table: "dbo.VehicleFault", name: "IX_ModifierId", newName: "IX_Modifier_Id");
            RenameIndex(table: "dbo.VehicleFault", name: "IX_CreatorId", newName: "IX_Creator_Id");
            RenameIndex(table: "dbo.VehicleFault", name: "IX_ImageId", newName: "IX_Image_Id");
            RenameIndex(table: "dbo.VehicleReport", name: "IX_RemoverId", newName: "IX_Remover_Id");
            RenameIndex(table: "dbo.VehicleReport", name: "IX_ModifierId", newName: "IX_Modifier_Id");
            RenameIndex(table: "dbo.VehicleReport", name: "IX_CreatorId", newName: "IX_Creator_Id");
            RenameIndex(table: "dbo.VehicleImage", name: "IX_RemoverId", newName: "IX_Remover_Id");
            RenameIndex(table: "dbo.VehicleImage", name: "IX_ModifierId", newName: "IX_Modifier_Id");
            RenameIndex(table: "dbo.VehicleImage", name: "IX_CreatorId", newName: "IX_Creator_Id");
            RenameIndex(table: "dbo.VehicleFeature", name: "IX_RemoverId", newName: "IX_Remover_Id");
            RenameIndex(table: "dbo.VehicleFeature", name: "IX_ModifierId", newName: "IX_Modifier_Id");
            RenameIndex(table: "dbo.VehicleFeature", name: "IX_CreatorId", newName: "IX_Creator_Id");
            RenameIndex(table: "dbo.Vehicle", name: "IX_RemoverId", newName: "IX_Remover_Id");
            RenameIndex(table: "dbo.Vehicle", name: "IX_ModifierId", newName: "IX_Modifier_Id");
            RenameIndex(table: "dbo.Vehicle", name: "IX_CreatorId", newName: "IX_Creator_Id");
            RenameIndex(table: "dbo.Vehicle", name: "IX_ApplicationUserId", newName: "IX_ApplicationUser_Id");
            RenameIndex(table: "dbo.VehicleDescription", name: "IX_RemoverId", newName: "IX_Remover_Id");
            RenameIndex(table: "dbo.VehicleDescription", name: "IX_ModifierId", newName: "IX_Modifier_Id");
            RenameIndex(table: "dbo.VehicleDescription", name: "IX_CreatorId", newName: "IX_Creator_Id");
            RenameIndex(table: "dbo.Subscription", name: "IX_RemoverId", newName: "IX_Remover_Id");
            RenameIndex(table: "dbo.Subscription", name: "IX_ModifierId", newName: "IX_Modifier_Id");
            RenameIndex(table: "dbo.Subscription", name: "IX_CreatorId", newName: "IX_Creator_Id");
            RenameIndex(table: "dbo.Image", name: "IX_RemoverId", newName: "IX_Remover_Id");
            RenameIndex(table: "dbo.Image", name: "IX_ModifierId", newName: "IX_Modifier_Id");
            RenameIndex(table: "dbo.Image", name: "IX_CreatorId", newName: "IX_Creator_Id");
            RenameIndex(table: "dbo.Feature", name: "IX_RemoverId", newName: "IX_Remover_Id");
            RenameIndex(table: "dbo.Feature", name: "IX_ModifierId", newName: "IX_Modifier_Id");
            RenameIndex(table: "dbo.Feature", name: "IX_CreatorId", newName: "IX_Creator_Id");
            RenameIndex(table: "dbo.ClassificationType", name: "IX_RemoverId", newName: "IX_Remover_Id");
            RenameIndex(table: "dbo.ClassificationType", name: "IX_ModifierId", newName: "IX_Modifier_Id");
            RenameIndex(table: "dbo.ClassificationType", name: "IX_CreatorId", newName: "IX_Creator_Id");
            RenameIndex(table: "dbo.Classification", name: "IX_RemoverId", newName: "IX_Remover_Id");
            RenameIndex(table: "dbo.Classification", name: "IX_ModifierId", newName: "IX_Modifier_Id");
            RenameIndex(table: "dbo.Classification", name: "IX_CreatorId", newName: "IX_Creator_Id");
            RenameColumn(table: "dbo.VehicleModel", name: "RemoverId", newName: "Remover_Id");
            RenameColumn(table: "dbo.VehicleModel", name: "ModifierId", newName: "Modifier_Id");
            RenameColumn(table: "dbo.VehicleModel", name: "CreatorId", newName: "Creator_Id");
            RenameColumn(table: "dbo.VehicleReview", name: "RemoverId", newName: "Remover_Id");
            RenameColumn(table: "dbo.VehicleReview", name: "ModifierId", newName: "Modifier_Id");
            RenameColumn(table: "dbo.VehicleReview", name: "CreatorId", newName: "Creator_Id");
            RenameColumn(table: "dbo.VehicleReportItem", name: "RemoverId", newName: "Remover_Id");
            RenameColumn(table: "dbo.VehicleReportItem", name: "ModifierId", newName: "Modifier_Id");
            RenameColumn(table: "dbo.VehicleReportItem", name: "CreatorId", newName: "Creator_Id");
            RenameColumn(table: "dbo.VehicleFault", name: "RemoverId", newName: "Remover_Id");
            RenameColumn(table: "dbo.VehicleFault", name: "ModifierId", newName: "Modifier_Id");
            RenameColumn(table: "dbo.VehicleFault", name: "ImageId", newName: "Image_Id");
            RenameColumn(table: "dbo.VehicleFault", name: "CreatorId", newName: "Creator_Id");
            RenameColumn(table: "dbo.VehicleReportItem", name: "ParentId", newName: "Parent_Id");
            RenameColumn(table: "dbo.VehicleReport", name: "RemoverId", newName: "Remover_Id");
            RenameColumn(table: "dbo.VehicleReport", name: "ModifierId", newName: "Modifier_Id");
            RenameColumn(table: "dbo.VehicleFault", name: "VehicleReportId", newName: "VehicleReport_Id");
            RenameColumn(table: "dbo.VehicleReport", name: "CreatorId", newName: "Creator_Id");
            RenameColumn(table: "dbo.VehicleImage", name: "RemoverId", newName: "Remover_Id");
            RenameColumn(table: "dbo.VehicleImage", name: "ModifierId", newName: "Modifier_Id");
            RenameColumn(table: "dbo.VehicleImage", name: "ImageId", newName: "Image_Id");
            RenameColumn(table: "dbo.VehicleImage", name: "CreatorId", newName: "Creator_Id");
            RenameColumn(table: "dbo.VehicleFeature", name: "RemoverId", newName: "Remover_Id");
            RenameColumn(table: "dbo.VehicleFeature", name: "ModifierId", newName: "Modifier_Id");
            RenameColumn(table: "dbo.VehicleFeature", name: "FeatureId", newName: "Feature_Id");
            RenameColumn(table: "dbo.VehicleFeature", name: "CreatorId", newName: "Creator_Id");
            RenameColumn(table: "dbo.Vehicle", name: "VehicleModelId", newName: "VehicleModel_Id");
            RenameColumn(table: "dbo.Vehicle", name: "RemoverId", newName: "Remover_Id");
            RenameColumn(table: "dbo.Vehicle", name: "ModifierId", newName: "Modifier_Id");
            RenameColumn(table: "dbo.Vehicle", name: "MainImageId", newName: "MainImage_Id");
            RenameColumn(table: "dbo.VehicleImage", name: "VehicleId", newName: "Vehicle_Id");
            RenameColumn(table: "dbo.VehicleFeature", name: "VehicleId", newName: "Vehicle_Id");
            RenameColumn(table: "dbo.Vehicle", name: "CreatorId", newName: "Creator_Id");
            RenameColumn(table: "dbo.Vehicle", name: "ApplicationUserId", newName: "ApplicationUser_Id");
            RenameColumn(table: "dbo.VehicleDescription", name: "VehicleId", newName: "Vehicle_Id");
            RenameColumn(table: "dbo.VehicleDescription", name: "RemoverId", newName: "Remover_Id");
            RenameColumn(table: "dbo.VehicleDescription", name: "ModifierId", newName: "Modifier_Id");
            RenameColumn(table: "dbo.VehicleDescription", name: "CreatorId", newName: "Creator_Id");
            RenameColumn(table: "dbo.Subscription", name: "RemoverId", newName: "Remover_Id");
            RenameColumn(table: "dbo.Subscription", name: "ModifierId", newName: "Modifier_Id");
            RenameColumn(table: "dbo.Subscription", name: "CreatorId", newName: "Creator_Id");
            RenameColumn(table: "dbo.Subscription", name: "ApplicationUserId", newName: "ApplicationUser_Id");
            RenameColumn(table: "dbo.Image", name: "RemoverId", newName: "Remover_Id");
            RenameColumn(table: "dbo.Image", name: "ModifierId", newName: "Modifier_Id");
            RenameColumn(table: "dbo.Image", name: "CreatorId", newName: "Creator_Id");
            RenameColumn(table: "dbo.Feature", name: "RemoverId", newName: "Remover_Id");
            RenameColumn(table: "dbo.Feature", name: "ModifierId", newName: "Modifier_Id");
            RenameColumn(table: "dbo.Feature", name: "CreatorId", newName: "Creator_Id");
            RenameColumn(table: "dbo.ClassificationType", name: "RemoverId", newName: "Remover_Id");
            RenameColumn(table: "dbo.ClassificationType", name: "ModifierId", newName: "Modifier_Id");
            RenameColumn(table: "dbo.ClassificationType", name: "CreatorId", newName: "Creator_Id");
            RenameColumn(table: "dbo.Classification", name: "RemoverId", newName: "Remover_Id");
            RenameColumn(table: "dbo.Classification", name: "ModifierId", newName: "Modifier_Id");
            RenameColumn(table: "dbo.Classification", name: "CreatorId", newName: "Creator_Id");
            CreateIndex("dbo.VehicleFault", "VehicleReport_Id");
            CreateIndex("dbo.VehicleImage", "Vehicle_Id");
            CreateIndex("dbo.VehicleImage", "Image_Id");
            CreateIndex("dbo.VehicleFeature", "Vehicle_Id");
            CreateIndex("dbo.VehicleFeature", "Feature_Id");
            CreateIndex("dbo.Vehicle", "VehicleModel_Id");
            CreateIndex("dbo.Vehicle", "MainImage_Id");
            CreateIndex("dbo.VehicleDescription", "Vehicle_Id");
            CreateIndex("dbo.Subscription", "ApplicationUser_Id");
            AddForeignKey("dbo.VehicleFault", "VehicleReport_Id", "dbo.VehicleReport", "Id");
            AddForeignKey("dbo.VehicleImage", "Image_Id", "dbo.Image", "Id");
            AddForeignKey("dbo.VehicleFeature", "Feature_Id", "dbo.Feature", "Id");
            AddForeignKey("dbo.Vehicle", "VehicleModel_Id", "dbo.VehicleModel", "Id");
            AddForeignKey("dbo.Vehicle", "MainImage_Id", "dbo.Image", "Id");
            AddForeignKey("dbo.VehicleImage", "Vehicle_Id", "dbo.Vehicle", "Id");
            AddForeignKey("dbo.VehicleFeature", "Vehicle_Id", "dbo.Vehicle", "Id");
            AddForeignKey("dbo.VehicleDescription", "Vehicle_Id", "dbo.Vehicle", "Id");
            AddForeignKey("dbo.Subscription", "ApplicationUser_Id", "dbo.Users", "Id");
        }
    }
}
