// <auto-generated />
namespace Triven.Data.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class temp_url_fields_for_reviews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(temp_url_fields_for_reviews));
        
        string IMigrationMetadata.Id
        {
            get { return "201704081031254_temp_url_fields_for_reviews"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
