// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Triven.Data.EntityFramework.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MessageTemplateTitle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MessageTemplateTitle));
        
        string IMigrationMetadata.Id
        {
            get { return "201701262025569_MessageTemplateTitle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
