// <auto-generated />
namespace Triven.Data.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201703021133 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201703021133));
        
        string IMigrationMetadata.Id
        {
            get { return "201703020933146_201703021133"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
