namespace Triven.Data.EntityFramework.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class asdfg : DbMigration
    {
        public override void Up()
        {
            RenameTable(name: "dbo.UserContactInfo", newName: "UserContactInfoes");
            DropForeignKey("dbo.Classification", "ClassificationTypeId", "dbo.ClassificationType");
            DropForeignKey("dbo.Users", "CreatedBy", "dbo.Users");
            DropForeignKey("dbo.Users", "UpdatedBy", "dbo.Users");
            DropForeignKey("dbo.Users", "DeletedBy", "dbo.Users");
            DropForeignKey("dbo.ClassificationType", "CreatedBy", "dbo.Users");
            DropForeignKey("dbo.ClassificationType", "UpdatedBy", "dbo.Users");
            DropForeignKey("dbo.ClassificationType", "DeletedBy", "dbo.Users");
            DropForeignKey("dbo.Classification", "CreatedBy", "dbo.Users");
            DropForeignKey("dbo.Classification", "UpdatedBy", "dbo.Users");
            DropForeignKey("dbo.Classification", "DeletedBy", "dbo.Users");
            DropForeignKey("dbo.Feature", "CreatedBy", "dbo.Users");
            DropForeignKey("dbo.Feature", "UpdatedBy", "dbo.Users");
            DropForeignKey("dbo.Feature", "DeletedBy", "dbo.Users");
            DropForeignKey("dbo.Image", "CreatedBy", "dbo.Users");
            DropForeignKey("dbo.Image", "UpdatedBy", "dbo.Users");
            DropForeignKey("dbo.Image", "DeletedBy", "dbo.Users");
            DropForeignKey("dbo.Subscription", "CreatedBy", "dbo.Users");
            DropForeignKey("dbo.Subscription", "UpdatedBy", "dbo.Users");
            DropForeignKey("dbo.Subscription", "DeletedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleDescription", "CreatedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleDescription", "UpdatedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleDescription", "DeletedBy", "dbo.Users");
            DropForeignKey("dbo.Vehicle", "OwnerId", "dbo.Users");
            DropForeignKey("dbo.Vehicle", "CreatedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleDescription", "VehicleId", "dbo.Vehicle");
            DropForeignKey("dbo.VehicleFeature", "CreatedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleFeature", "FeatureId", "dbo.Feature");
            DropForeignKey("dbo.VehicleFeature", "UpdatedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleFeature", "DeletedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleFeature", "VehicleId", "dbo.Vehicle");
            DropForeignKey("dbo.VehicleImage", "CreatedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleImage", "ImageId", "dbo.Image");
            DropForeignKey("dbo.VehicleImage", "UpdatedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleImage", "DeletedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleImage", "VehicleId", "dbo.Vehicle");
            DropForeignKey("dbo.Vehicle", "MainImageId", "dbo.Image");
            DropForeignKey("dbo.Vehicle", "UpdatedBy", "dbo.Users");
            DropForeignKey("dbo.Vehicle", "DeletedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleReport", "CreatedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleFault", "CreatedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleFault", "ImageId", "dbo.Image");
            DropForeignKey("dbo.VehicleFault", "UpdatedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleFault", "DeletedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleFault", "VehicleReportId", "dbo.VehicleReport");
            DropForeignKey("dbo.VehicleReport", "UpdatedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleReport", "DeletedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleReportItem", "CreatedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleReportItem", "UpdatedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleReportItem", "DeletedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleReportItem", "ParentId", "dbo.VehicleReport");
            DropForeignKey("dbo.VehicleReport", "VehicleId", "dbo.Vehicle");
            DropForeignKey("dbo.VehicleReview", "CreatedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleReview", "UpdatedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleReview", "DeletedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleReview", "VehicleId", "dbo.Vehicle");
            DropForeignKey("dbo.VehicleModel", "CreatedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleModel", "DrivetrainId", "dbo.Classification");
            DropForeignKey("dbo.VehicleModel", "FuelTypeId", "dbo.Classification");
            DropForeignKey("dbo.VehicleModel", "UpdatedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleModel", "DeletedBy", "dbo.Users");
            DropForeignKey("dbo.VehicleModel", "TransmissionId", "dbo.Classification");
            DropForeignKey("dbo.VehicleModel", "VehicleBodyId", "dbo.Classification");
            DropForeignKey("dbo.VehicleModel", "VehicleManufacturerId", "dbo.Classification");
            DropForeignKey("dbo.Vehicle", "ModelId", "dbo.VehicleModel");
            DropIndex("dbo.Classification", new[] { "ClassificationTypeId" });
            DropIndex("dbo.Classification", new[] { "CreatedBy" });
            DropIndex("dbo.Classification", new[] { "UpdatedBy" });
            DropIndex("dbo.Classification", new[] { "DeletedBy" });
            DropIndex("dbo.ClassificationType", new[] { "CreatedBy" });
            DropIndex("dbo.ClassificationType", new[] { "UpdatedBy" });
            DropIndex("dbo.ClassificationType", new[] { "DeletedBy" });
            DropIndex("dbo.Users", new[] { "CreatedBy" });
            DropIndex("dbo.Users", new[] { "UpdatedBy" });
            DropIndex("dbo.Users", new[] { "DeletedBy" });
            DropIndex("dbo.UserContactInfoes", new[] { "ApplicationUserId" });
            DropIndex("dbo.Feature", new[] { "CreatedBy" });
            DropIndex("dbo.Feature", new[] { "UpdatedBy" });
            DropIndex("dbo.Feature", new[] { "DeletedBy" });
            DropIndex("dbo.Image", new[] { "CreatedBy" });
            DropIndex("dbo.Image", new[] { "UpdatedBy" });
            DropIndex("dbo.Image", new[] { "DeletedBy" });
            DropIndex("dbo.Subscription", new[] { "CreatedBy" });
            DropIndex("dbo.Subscription", new[] { "UpdatedBy" });
            DropIndex("dbo.Subscription", new[] { "DeletedBy" });
            DropIndex("dbo.VehicleDescription", new[] { "VehicleId" });
            DropIndex("dbo.VehicleDescription", new[] { "CreatedBy" });
            DropIndex("dbo.VehicleDescription", new[] { "UpdatedBy" });
            DropIndex("dbo.VehicleDescription", new[] { "DeletedBy" });
            DropIndex("dbo.Vehicle", new[] { "OwnerId" });
            DropIndex("dbo.Vehicle", new[] { "MainImageId" });
            DropIndex("dbo.Vehicle", new[] { "ModelId" });
            DropIndex("dbo.Vehicle", new[] { "CreatedBy" });
            DropIndex("dbo.Vehicle", new[] { "UpdatedBy" });
            DropIndex("dbo.Vehicle", new[] { "DeletedBy" });
            DropIndex("dbo.VehicleFeature", new[] { "FeatureId" });
            DropIndex("dbo.VehicleFeature", new[] { "VehicleId" });
            DropIndex("dbo.VehicleFeature", new[] { "CreatedBy" });
            DropIndex("dbo.VehicleFeature", new[] { "UpdatedBy" });
            DropIndex("dbo.VehicleFeature", new[] { "DeletedBy" });
            DropIndex("dbo.VehicleImage", new[] { "VehicleId" });
            DropIndex("dbo.VehicleImage", new[] { "ImageId" });
            DropIndex("dbo.VehicleImage", new[] { "CreatedBy" });
            DropIndex("dbo.VehicleImage", new[] { "UpdatedBy" });
            DropIndex("dbo.VehicleImage", new[] { "DeletedBy" });
            DropIndex("dbo.VehicleReport", new[] { "VehicleId" });
            DropIndex("dbo.VehicleReport", new[] { "CreatedBy" });
            DropIndex("dbo.VehicleReport", new[] { "UpdatedBy" });
            DropIndex("dbo.VehicleReport", new[] { "DeletedBy" });
            DropIndex("dbo.VehicleFault", new[] { "ImageId" });
            DropIndex("dbo.VehicleFault", new[] { "VehicleReportId" });
            DropIndex("dbo.VehicleFault", new[] { "CreatedBy" });
            DropIndex("dbo.VehicleFault", new[] { "UpdatedBy" });
            DropIndex("dbo.VehicleFault", new[] { "DeletedBy" });
            DropIndex("dbo.VehicleReportItem", new[] { "ParentId" });
            DropIndex("dbo.VehicleReportItem", new[] { "CreatedBy" });
            DropIndex("dbo.VehicleReportItem", new[] { "UpdatedBy" });
            DropIndex("dbo.VehicleReportItem", new[] { "DeletedBy" });
            DropIndex("dbo.VehicleReview", new[] { "VehicleId" });
            DropIndex("dbo.VehicleReview", new[] { "CreatedBy" });
            DropIndex("dbo.VehicleReview", new[] { "UpdatedBy" });
            DropIndex("dbo.VehicleReview", new[] { "DeletedBy" });
            DropIndex("dbo.VehicleModel", new[] { "VehicleManufacturerId" });
            DropIndex("dbo.VehicleModel", new[] { "TransmissionId" });
            DropIndex("dbo.VehicleModel", new[] { "DrivetrainId" });
            DropIndex("dbo.VehicleModel", new[] { "VehicleBodyId" });
            DropIndex("dbo.VehicleModel", new[] { "FuelTypeId" });
            DropIndex("dbo.VehicleModel", new[] { "CreatedBy" });
            DropIndex("dbo.VehicleModel", new[] { "UpdatedBy" });
            DropIndex("dbo.VehicleModel", new[] { "DeletedBy" });
            RenameColumn(table: "dbo.UserContactInfoes", name: "ApplicationUserId", newName: "ApplicationUser_Id");
            DropPrimaryKey("dbo.VehicleFeature");
            DropPrimaryKey("dbo.VehicleImage");
            AddColumn("dbo.UserContactInfoes", "CreatedOn", c => c.DateTime());
            AddColumn("dbo.UserContactInfoes", "UpdatedOn", c => c.DateTime());
            AddColumn("dbo.UserContactInfoes", "DeletedOn", c => c.DateTime());
            AddColumn("dbo.UserContactInfoes", "ModifierUserIp", c => c.String());
            AlterColumn("dbo.UserContactInfoes", "ApplicationUser_Id", c => c.Int());
            AddPrimaryKey("dbo.VehicleFeature", "Id");
            AddPrimaryKey("dbo.VehicleImage", "Id");
            CreateIndex("dbo.UserContactInfoes", "ApplicationUser_Id");
            DropColumn("dbo.Classification", "ClassificationTypeId");
            DropColumn("dbo.Classification", "CreatedBy");
            DropColumn("dbo.Classification", "UpdatedBy");
            DropColumn("dbo.Classification", "DeletedBy");
            DropColumn("dbo.ClassificationType", "CreatedBy");
            DropColumn("dbo.ClassificationType", "UpdatedBy");
            DropColumn("dbo.ClassificationType", "DeletedBy");
            DropColumn("dbo.Users", "CreatedBy");
            DropColumn("dbo.Users", "UpdatedBy");
            DropColumn("dbo.Users", "DeletedBy");
            DropColumn("dbo.Feature", "CreatedBy");
            DropColumn("dbo.Feature", "UpdatedBy");
            DropColumn("dbo.Feature", "DeletedBy");
            DropColumn("dbo.Image", "CreatedBy");
            DropColumn("dbo.Image", "UpdatedBy");
            DropColumn("dbo.Image", "DeletedBy");
            DropColumn("dbo.Subscription", "UserId");
            DropColumn("dbo.Subscription", "CreatedBy");
            DropColumn("dbo.Subscription", "UpdatedBy");
            DropColumn("dbo.Subscription", "DeletedBy");
            DropColumn("dbo.VehicleDescription", "VehicleId");
            DropColumn("dbo.VehicleDescription", "CreatedBy");
            DropColumn("dbo.VehicleDescription", "UpdatedBy");
            DropColumn("dbo.VehicleDescription", "DeletedBy");
            DropColumn("dbo.Vehicle", "OwnerId");
            DropColumn("dbo.Vehicle", "MainImageId");
            DropColumn("dbo.Vehicle", "ModelId");
            DropColumn("dbo.Vehicle", "CreatedBy");
            DropColumn("dbo.Vehicle", "UpdatedBy");
            DropColumn("dbo.Vehicle", "DeletedBy");
            DropColumn("dbo.VehicleFeature", "FeatureId");
            DropColumn("dbo.VehicleFeature", "VehicleId");
            DropColumn("dbo.VehicleFeature", "CreatedBy");
            DropColumn("dbo.VehicleFeature", "UpdatedBy");
            DropColumn("dbo.VehicleFeature", "DeletedBy");
            DropColumn("dbo.VehicleImage", "VehicleId");
            DropColumn("dbo.VehicleImage", "ImageId");
            DropColumn("dbo.VehicleImage", "CreatedBy");
            DropColumn("dbo.VehicleImage", "UpdatedBy");
            DropColumn("dbo.VehicleImage", "DeletedBy");
            DropColumn("dbo.VehicleReport", "VehicleId");
            DropColumn("dbo.VehicleReport", "CreatedBy");
            DropColumn("dbo.VehicleReport", "UpdatedBy");
            DropColumn("dbo.VehicleReport", "DeletedBy");
            DropColumn("dbo.VehicleFault", "ImageId");
            DropColumn("dbo.VehicleFault", "VehicleReportId");
            DropColumn("dbo.VehicleFault", "CreatedBy");
            DropColumn("dbo.VehicleFault", "UpdatedBy");
            DropColumn("dbo.VehicleFault", "DeletedBy");
            DropColumn("dbo.VehicleReportItem", "ParentId");
            DropColumn("dbo.VehicleReportItem", "CreatedBy");
            DropColumn("dbo.VehicleReportItem", "UpdatedBy");
            DropColumn("dbo.VehicleReportItem", "DeletedBy");
            DropColumn("dbo.VehicleReview", "VehicleId");
            DropColumn("dbo.VehicleReview", "CreatedBy");
            DropColumn("dbo.VehicleReview", "UpdatedBy");
            DropColumn("dbo.VehicleReview", "DeletedBy");
            DropColumn("dbo.VehicleModel", "VehicleManufacturerId");
            DropColumn("dbo.VehicleModel", "TransmissionId");
            DropColumn("dbo.VehicleModel", "DrivetrainId");
            DropColumn("dbo.VehicleModel", "VehicleBodyId");
            DropColumn("dbo.VehicleModel", "FuelTypeId");
            DropColumn("dbo.VehicleModel", "CreatedBy");
            DropColumn("dbo.VehicleModel", "UpdatedBy");
            DropColumn("dbo.VehicleModel", "DeletedBy");
        }
        
        public override void Down()
        {
            AddColumn("dbo.VehicleModel", "DeletedBy", c => c.Int());
            AddColumn("dbo.VehicleModel", "UpdatedBy", c => c.Int());
            AddColumn("dbo.VehicleModel", "CreatedBy", c => c.Int());
            AddColumn("dbo.VehicleModel", "FuelTypeId", c => c.Int(nullable: false));
            AddColumn("dbo.VehicleModel", "VehicleBodyId", c => c.Int(nullable: false));
            AddColumn("dbo.VehicleModel", "DrivetrainId", c => c.Int(nullable: false));
            AddColumn("dbo.VehicleModel", "TransmissionId", c => c.Int(nullable: false));
            AddColumn("dbo.VehicleModel", "VehicleManufacturerId", c => c.Int(nullable: false));
            AddColumn("dbo.VehicleReview", "DeletedBy", c => c.Int());
            AddColumn("dbo.VehicleReview", "UpdatedBy", c => c.Int());
            AddColumn("dbo.VehicleReview", "CreatedBy", c => c.Int());
            AddColumn("dbo.VehicleReview", "VehicleId", c => c.Int(nullable: false));
            AddColumn("dbo.VehicleReportItem", "DeletedBy", c => c.Int());
            AddColumn("dbo.VehicleReportItem", "UpdatedBy", c => c.Int());
            AddColumn("dbo.VehicleReportItem", "CreatedBy", c => c.Int());
            AddColumn("dbo.VehicleReportItem", "ParentId", c => c.Int(nullable: false));
            AddColumn("dbo.VehicleFault", "DeletedBy", c => c.Int());
            AddColumn("dbo.VehicleFault", "UpdatedBy", c => c.Int());
            AddColumn("dbo.VehicleFault", "CreatedBy", c => c.Int());
            AddColumn("dbo.VehicleFault", "VehicleReportId", c => c.Int(nullable: false));
            AddColumn("dbo.VehicleFault", "ImageId", c => c.Int(nullable: false));
            AddColumn("dbo.VehicleReport", "DeletedBy", c => c.Int());
            AddColumn("dbo.VehicleReport", "UpdatedBy", c => c.Int());
            AddColumn("dbo.VehicleReport", "CreatedBy", c => c.Int());
            AddColumn("dbo.VehicleReport", "VehicleId", c => c.Int(nullable: false));
            AddColumn("dbo.VehicleImage", "DeletedBy", c => c.Int());
            AddColumn("dbo.VehicleImage", "UpdatedBy", c => c.Int());
            AddColumn("dbo.VehicleImage", "CreatedBy", c => c.Int());
            AddColumn("dbo.VehicleImage", "ImageId", c => c.Int(nullable: false));
            AddColumn("dbo.VehicleImage", "VehicleId", c => c.Int(nullable: false));
            AddColumn("dbo.VehicleFeature", "DeletedBy", c => c.Int());
            AddColumn("dbo.VehicleFeature", "UpdatedBy", c => c.Int());
            AddColumn("dbo.VehicleFeature", "CreatedBy", c => c.Int());
            AddColumn("dbo.VehicleFeature", "VehicleId", c => c.Int(nullable: false));
            AddColumn("dbo.VehicleFeature", "FeatureId", c => c.Int(nullable: false));
            AddColumn("dbo.Vehicle", "DeletedBy", c => c.Int());
            AddColumn("dbo.Vehicle", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Vehicle", "CreatedBy", c => c.Int());
            AddColumn("dbo.Vehicle", "ModelId", c => c.Int(nullable: false));
            AddColumn("dbo.Vehicle", "MainImageId", c => c.Int(nullable: false));
            AddColumn("dbo.Vehicle", "OwnerId", c => c.Int(nullable: false));
            AddColumn("dbo.VehicleDescription", "DeletedBy", c => c.Int());
            AddColumn("dbo.VehicleDescription", "UpdatedBy", c => c.Int());
            AddColumn("dbo.VehicleDescription", "CreatedBy", c => c.Int());
            AddColumn("dbo.VehicleDescription", "VehicleId", c => c.Int(nullable: false));
            AddColumn("dbo.Subscription", "DeletedBy", c => c.Int());
            AddColumn("dbo.Subscription", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Subscription", "CreatedBy", c => c.Int());
            AddColumn("dbo.Subscription", "UserId", c => c.Int(nullable: false));
            AddColumn("dbo.Image", "DeletedBy", c => c.Int());
            AddColumn("dbo.Image", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Image", "CreatedBy", c => c.Int());
            AddColumn("dbo.Feature", "DeletedBy", c => c.Int());
            AddColumn("dbo.Feature", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Feature", "CreatedBy", c => c.Int());
            AddColumn("dbo.Users", "DeletedBy", c => c.Int());
            AddColumn("dbo.Users", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Users", "CreatedBy", c => c.Int());
            AddColumn("dbo.ClassificationType", "DeletedBy", c => c.Int());
            AddColumn("dbo.ClassificationType", "UpdatedBy", c => c.Int());
            AddColumn("dbo.ClassificationType", "CreatedBy", c => c.Int());
            AddColumn("dbo.Classification", "DeletedBy", c => c.Int());
            AddColumn("dbo.Classification", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Classification", "CreatedBy", c => c.Int());
            AddColumn("dbo.Classification", "ClassificationTypeId", c => c.Int(nullable: false));
            DropIndex("dbo.UserContactInfoes", new[] { "ApplicationUser_Id" });
            DropPrimaryKey("dbo.VehicleImage");
            DropPrimaryKey("dbo.VehicleFeature");
            AlterColumn("dbo.UserContactInfoes", "ApplicationUser_Id", c => c.Int(nullable: false));
            DropColumn("dbo.UserContactInfoes", "ModifierUserIp");
            DropColumn("dbo.UserContactInfoes", "DeletedOn");
            DropColumn("dbo.UserContactInfoes", "UpdatedOn");
            DropColumn("dbo.UserContactInfoes", "CreatedOn");
            AddPrimaryKey("dbo.VehicleImage", new[] { "VehicleId", "ImageId" });
            AddPrimaryKey("dbo.VehicleFeature", new[] { "FeatureId", "VehicleId" });
            RenameColumn(table: "dbo.UserContactInfoes", name: "ApplicationUser_Id", newName: "ApplicationUserId");
            CreateIndex("dbo.VehicleModel", "DeletedBy");
            CreateIndex("dbo.VehicleModel", "UpdatedBy");
            CreateIndex("dbo.VehicleModel", "CreatedBy");
            CreateIndex("dbo.VehicleModel", "FuelTypeId");
            CreateIndex("dbo.VehicleModel", "VehicleBodyId");
            CreateIndex("dbo.VehicleModel", "DrivetrainId");
            CreateIndex("dbo.VehicleModel", "TransmissionId");
            CreateIndex("dbo.VehicleModel", "VehicleManufacturerId");
            CreateIndex("dbo.VehicleReview", "DeletedBy");
            CreateIndex("dbo.VehicleReview", "UpdatedBy");
            CreateIndex("dbo.VehicleReview", "CreatedBy");
            CreateIndex("dbo.VehicleReview", "VehicleId");
            CreateIndex("dbo.VehicleReportItem", "DeletedBy");
            CreateIndex("dbo.VehicleReportItem", "UpdatedBy");
            CreateIndex("dbo.VehicleReportItem", "CreatedBy");
            CreateIndex("dbo.VehicleReportItem", "ParentId");
            CreateIndex("dbo.VehicleFault", "DeletedBy");
            CreateIndex("dbo.VehicleFault", "UpdatedBy");
            CreateIndex("dbo.VehicleFault", "CreatedBy");
            CreateIndex("dbo.VehicleFault", "VehicleReportId");
            CreateIndex("dbo.VehicleFault", "ImageId");
            CreateIndex("dbo.VehicleReport", "DeletedBy");
            CreateIndex("dbo.VehicleReport", "UpdatedBy");
            CreateIndex("dbo.VehicleReport", "CreatedBy");
            CreateIndex("dbo.VehicleReport", "VehicleId");
            CreateIndex("dbo.VehicleImage", "DeletedBy");
            CreateIndex("dbo.VehicleImage", "UpdatedBy");
            CreateIndex("dbo.VehicleImage", "CreatedBy");
            CreateIndex("dbo.VehicleImage", "ImageId");
            CreateIndex("dbo.VehicleImage", "VehicleId");
            CreateIndex("dbo.VehicleFeature", "DeletedBy");
            CreateIndex("dbo.VehicleFeature", "UpdatedBy");
            CreateIndex("dbo.VehicleFeature", "CreatedBy");
            CreateIndex("dbo.VehicleFeature", "VehicleId");
            CreateIndex("dbo.VehicleFeature", "FeatureId");
            CreateIndex("dbo.Vehicle", "DeletedBy");
            CreateIndex("dbo.Vehicle", "UpdatedBy");
            CreateIndex("dbo.Vehicle", "CreatedBy");
            CreateIndex("dbo.Vehicle", "ModelId");
            CreateIndex("dbo.Vehicle", "MainImageId");
            CreateIndex("dbo.Vehicle", "OwnerId");
            CreateIndex("dbo.VehicleDescription", "DeletedBy");
            CreateIndex("dbo.VehicleDescription", "UpdatedBy");
            CreateIndex("dbo.VehicleDescription", "CreatedBy");
            CreateIndex("dbo.VehicleDescription", "VehicleId");
            CreateIndex("dbo.Subscription", "DeletedBy");
            CreateIndex("dbo.Subscription", "UpdatedBy");
            CreateIndex("dbo.Subscription", "CreatedBy");
            CreateIndex("dbo.Image", "DeletedBy");
            CreateIndex("dbo.Image", "UpdatedBy");
            CreateIndex("dbo.Image", "CreatedBy");
            CreateIndex("dbo.Feature", "DeletedBy");
            CreateIndex("dbo.Feature", "UpdatedBy");
            CreateIndex("dbo.Feature", "CreatedBy");
            CreateIndex("dbo.UserContactInfoes", "ApplicationUserId");
            CreateIndex("dbo.Users", "DeletedBy");
            CreateIndex("dbo.Users", "UpdatedBy");
            CreateIndex("dbo.Users", "CreatedBy");
            CreateIndex("dbo.ClassificationType", "DeletedBy");
            CreateIndex("dbo.ClassificationType", "UpdatedBy");
            CreateIndex("dbo.ClassificationType", "CreatedBy");
            CreateIndex("dbo.Classification", "DeletedBy");
            CreateIndex("dbo.Classification", "UpdatedBy");
            CreateIndex("dbo.Classification", "CreatedBy");
            CreateIndex("dbo.Classification", "ClassificationTypeId");
            AddForeignKey("dbo.Vehicle", "ModelId", "dbo.VehicleModel", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VehicleModel", "VehicleManufacturerId", "dbo.Classification", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VehicleModel", "VehicleBodyId", "dbo.Classification", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VehicleModel", "TransmissionId", "dbo.Classification", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VehicleModel", "DeletedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.VehicleModel", "UpdatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.VehicleModel", "FuelTypeId", "dbo.Classification", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VehicleModel", "DrivetrainId", "dbo.Classification", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VehicleModel", "CreatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.VehicleReview", "VehicleId", "dbo.Vehicle", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VehicleReview", "DeletedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.VehicleReview", "UpdatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.VehicleReview", "CreatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.VehicleReport", "VehicleId", "dbo.Vehicle", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VehicleReportItem", "ParentId", "dbo.VehicleReport", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VehicleReportItem", "DeletedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.VehicleReportItem", "UpdatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.VehicleReportItem", "CreatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.VehicleReport", "DeletedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.VehicleReport", "UpdatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.VehicleFault", "VehicleReportId", "dbo.VehicleReport", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VehicleFault", "DeletedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.VehicleFault", "UpdatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.VehicleFault", "ImageId", "dbo.Image", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VehicleFault", "CreatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.VehicleReport", "CreatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.Vehicle", "DeletedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.Vehicle", "UpdatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.Vehicle", "MainImageId", "dbo.Image", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VehicleImage", "VehicleId", "dbo.Vehicle", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VehicleImage", "DeletedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.VehicleImage", "UpdatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.VehicleImage", "ImageId", "dbo.Image", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VehicleImage", "CreatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.VehicleFeature", "VehicleId", "dbo.Vehicle", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VehicleFeature", "DeletedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.VehicleFeature", "UpdatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.VehicleFeature", "FeatureId", "dbo.Feature", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VehicleFeature", "CreatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.VehicleDescription", "VehicleId", "dbo.Vehicle", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Vehicle", "CreatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.Vehicle", "OwnerId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VehicleDescription", "DeletedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.VehicleDescription", "UpdatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.VehicleDescription", "CreatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.Subscription", "DeletedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.Subscription", "UpdatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.Subscription", "CreatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.Image", "DeletedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.Image", "UpdatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.Image", "CreatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.Feature", "DeletedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.Feature", "UpdatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.Feature", "CreatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.Classification", "DeletedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.Classification", "UpdatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.Classification", "CreatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.ClassificationType", "DeletedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.ClassificationType", "UpdatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.ClassificationType", "CreatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.Users", "DeletedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.Users", "UpdatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.Users", "CreatedBy", "dbo.Users", "Id");
            AddForeignKey("dbo.Classification", "ClassificationTypeId", "dbo.ClassificationType", "Id", cascadeDelete: true);
            RenameTable(name: "dbo.UserContactInfoes", newName: "UserContactInfo");
        }
    }
}
