// <auto-generated />
namespace Triven.Data.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class More_generic_vehicle_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(More_generic_vehicle_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201704051629385_More_generic_vehicle_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
